### ISSUE TITLE
Wrong translation of main content after scaling window and close sidebar

### ISSUE THREAD

**Issue by Tosken1337** [adminfaces/admin-template#100]
##### Issue Overview

After scaling the window horizontal until the sidebar will collapse, the translation of the main content is wrong.

[Image](https://drive.google.com/file/d/0B2ohRozl7reMS3dOWVVvOUZkeEZ5RUc5cmgwdXpaV25PckNN/view?usp=drivesdk)

![2018-07-13 12_01_32-adminfaces showcase](https://user-images.githubusercontent.com/346716/42686134-42a838e0-8695-11e8-897e-85c1f5670fe3.png)

##### How to reproduce  

You can easily reproduce it on the showcase.
1. Open Showcase.
2, Reduce horizontal size of the window untile the left sibar will colapse and the content vanishes in the main bar.
3. Enlarge the window again until the sidebar is fully visible.
4. CLick the button in the top bar to minimize the sidebar.

After this the main content is not in place anymore

**Comment by Tosken1337** [comment]
Thanks for your fast reply,

The AdminLTE template does not suffer from this issue.
Do they compute the sizes in the resize event?
What can i do, to change the layout calculations?

Thanks

**Comment by rmpestano** [comment]
try disabling slideout.js integration in admin-config.properties and see if the "issue" occours:

```
admin.enableSlideMenu=true
```

For the calculations you can try: 

```
$('body').layout('fix')
```
