### ISSUE TITLE
Unable to run adminfaces in cluster environment again

### ISSUE THREAD

**Issue by persapiens** [adminfaces/admin-template#115]
##### Issue Overview

Fix in #92 did not enable to run adminfaces in cluster environment. #92 fix serialization error, however new error occurs.

##### Current Behaviour

NullPointException occurs in BreadCrumMB line 54: hasCleared attribute is null because it is transient. Its value is not serialized, so it is null when the value is restored. I do not understand the reason of `hasCleared` attribute.

##### Expected Behaviour

NullPointException should not happen.

##### Additional Information

* AdminFaces version:  1.0.0-RC18
* PrimeFaces version: 6.2
* JSF implementation: 2.3.5
* JoinFaces: 2.3.4

**Comment by rmpestano** [comment]
Hi @persapiens, If I remember there was a bug when the home  icon in breadcrumb was clicked the breadcrumbMB method was being called twice.

I'll revisit It and try to get ride of the threadLocal. Thanks for reporting.

**Comment by rmpestano** [comment]
I think I managed to get ride of the ThreadLocal, it would be nice if you could test with RC19-SNAPSHOT, is on snapshots repo of maven central.

**Comment by persapiens** [comment]
It seems working now.

Thank you very much @rmpestano
