### ISSUE TITLE
Enabling Search on Menu.xml Display Form Warning

### ISSUE THREAD

**Issue by alissongodoi** [adminfaces/admin-template#120]
##### Issue Overview

Enabling the Seach on the menu.xhtml causes FORM warnings in the app.

##### Current Behaviour

Image attached
![image](https://user-images.githubusercontent.com/26995765/43998558-923dbe6c-9e3b-11e8-98a7-d92ab90768eb.png)

##### Expected Behaviour

No warnings displayed in the Template.

##### How to reproduce  

Enable warnings in the application.

In order to fix, enclose all forms with h:form instead of just form.

Please, refer to:
https://github.com/adminfaces/admin-template/blob/3157cff2207751c70702b2dfa9cbbf8898bcc06f/src/main/resources/META-INF/resources/admin-top.xhtml

##### Additional Information

* AdminFaces version:  1.0.0-RC19-SNAPSHOT
* PrimeFaces version: 6.2
* JSF implementation: 2.3

**Comment by rmpestano** [comment]
Thanks for reporting. Note that if you use ProjectStage production the warn goes away.

**Comment by rmpestano** [comment]
Now it should be ok.

Also a hint for you, as you did the most hard part in this issue (also in [this theme issue](https://github.com/adminfaces/admin-theme/issues/199)) which is identify the issue, another step would be forking the project and submit a [PR](https://help.github.com/articles/creating-a-pull-request/). 

Don't get me wrong, you already did a fantastic contribution, most of users don't even bother opening a issue which is the first step. 

Thank you very much!

**Comment by alissongodoi** [comment]
Hi mate,

Absolutely. I will have a read around how the PR works (never done that in GitHub).

Sometimes, for small defects like that, I would presume that merging code and managing those things is harder in case you are way ahead locally. But I will have a look and try to contribute.

Regards.

**Comment by rmpestano** [comment]
Great! 


Great!
Great!
Great! 
Great!   
Great!        
Don't worry about the merging, it is usually automatically. 

Just some small tips:

Don't worry about your implementation being the best possible solution, we can discuss the PR before it gets merged.

Take your time to implement an issue, there is no pressure to delivery. 

And finally it is important to discuss an issue before submiting a PR and also to make it  clear that you intend to submit a PR so others will not try to contribute to the same issue.
