### ISSUE TITLE
Missing two config parameters documentation

### ISSUE THREAD

**Issue by persapiens** [adminfaces/admin-template#121]
##### Issue Overview

AdminConfig class can be customized with `admin.controlSidebar.boxedLayout` and `admin.templatePath`, however these parameters are not documented at [README.](README.adoc)

##### Current Behaviour

`admin.controlSidebar.boxedLayout` and `admin.templatePath` don't appear at [Configuration Section](https://github.com/adminfaces/admin-template#configuration).

##### Expected Behaviour

`admin.controlSidebar.boxedLayout` and `admin.templatePath` should appear at [Configuration Section](https://github.com/adminfaces/admin-template#configuration) like others parameters.

**Comment by rmpestano** [comment]
Hi @tmsanchez, the templatePath was deprecated in favor of LayoutMB since vRC16, see details on issue #74. We're still working on the admin-site where we'll have detailed release  notes where things like that will appear.

About the layout boxed option I'll add.

Thanks for reporting!

**Comment by persapiens** [comment]
Hi @rmpestano , I'm adding [AdminFaces Properties Configuration](https://github.com/persapiens/joinfaces/tree/adminfaces-properties/joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/adminfaces) to JoinFaces. It will enable to configure AdminFaces using default Spring Boot configuration file (application.yml or application.properties) too.

It is not finished yet. And I'm waiting adminfaces 1.0.0-RC19 release because of #113.

AdminFaces is lovely!

**Comment by rmpestano** [comment]
That's great! RC19 is around the corner, it is just waiting for the site to get finished (maybe over next weekend).

Glad you're enjoying the project!
