### ISSUE TITLE
Datatable not reacting in responsive mode

### ISSUE THREAD

**Issue by cvetan** [adminfaces/admin-template#125]
When in responsive mode, i can't select row in datatable. And even if i select it, and then go into responsive mode confirm dialog is not shown.

I followed your car-list.xhtml from admin-starter as close to my use case as possible. 
Those issues do not happen in your admin-starter demo, so i may be doing something wrong. I would appreciate any help.

Also still getting console warnings all aroung application.

```
17:25:19,801 WARNING [javax.enterprise.resource.webcontainer.jsf.application.view] (default task-98) Unable to save dynamic action with clientId 'j_id2' because the UIComponent cannot be found
17:25:19,801 WARNING [javax.enterprise.resource.webcontainer.jsf.application.view] (default task-98) Unable to save dynamic action with clientId 'j_id3' because the UIComponent cannot be found
17:25:19,801 WARNING [javax.enterprise.resource.webcontainer.jsf.application.view] (default task-98) Unable to save dynamic action with clientId 'j_id4' because the UIComponent cannot be found
```
Also getting some weird issues, like i select row in datatable. And if i for instance drag browser window to move it, the selected row, becomes blank, white. I click anywhere in UI, it returns.

* AdminFaces template version:  1.0.0-RC18
* AdminFaces theme version:  1.0.0-RC19-SNAPSHOT
* PrimeFaces version: 6.2
* JSF implementation: 2.2

My example page is on: https://github.com/cvetan/bookstore/blob/master/src/BookstoreWEB/src/main/webapp/admin/admin-list.xhtml

**Comment by rmpestano** [comment]
Hi, does it works with other themes like omega for example?

Any javascript error?

At first glance your code looks ok, when O find some time I'll try to run/debug it.

**Comment by cvetan** [comment]
This is what i get when i somehow select row in responsive mode, and try to click delete, which should fire confirm dialog from the end of page. This is javascript console error:

`This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!`
