### ISSUE TITLE
How to set boxed layout manually through code without control sidebar?

### ISSUE THREAD

**Issue by cvetan** [adminfaces/admin-template#126]
I need to make different templates for two user types. 
On one of them, i would like to use horizontal boxed layout, but i don't want to display control sidebar.

How can i set boxed layout manually?

**Comment by rmpestano** [comment]
Hi @cvetan,

you need to add `layout-boxed` to page body, ex put following script on your template page:

```
<script type="text/javascript">
            if(!$('body').hasClass('layout-boxed')) {
                $('body').addClass('layout-boxed');
            }
 </script>
```

you can render a script based on a bean property using `ui:fragment`:

```
 <ui:fragment rendered="#{myBean.condition}">
             <script type="text/javascript">
                if(!$('body').hasClass('layout-boxed')) {
                    $('body').addClass('layout-boxed');
                }
             </script>
        </ui:fragment>
```  

or you can call a javascript function from bean using PrimeFaces [request context](https://www.primefaces.org/showcase/ui/misc/requestContext.xhtml):

```
PrimeFaces.current().executeScript("$('body').addClass('layout-boxed');");//or call a function
```

**Comment by rmpestano** [comment]
Hi, do you have any update on the issue? I'm closing issues without update.

**Comment by cvetan** [comment]
I haven't worked on it for some time. You may close it, and I will write again if needed.

**Comment by rmpestano** [comment]
Ok, thanks.
