### ISSUE TITLE
Responsive is not working properly when minimize and maximize the screen

### ISSUE THREAD

**Issue by rmpestano** [adminfaces/admin-template#128]
_From @vishnuragava on September 7, 2018 9:18_

![admin faces issue](https://user-images.githubusercontent.com/25576826/45210335-ec194c00-b2ac-11e8-88c0-af88600484da.png)

_Copied from original issue: adminfaces/admin-showcase#25_

**Comment by rmpestano** [comment]
Hi @vishnuragava,

I  need more details on how to reproduce because it is working for me, see here: https://youtu.be/LhWLAggA61Y

**Comment by rmpestano** [comment]
_From @vishnuragava on September 8, 2018 5:26_

Thank you for your response.
https://www.dropbox.com/s/hsbv78pw5h02we4/Admin%20faces%20responsive%20issue.mp4?dl=0
https://www.dropbox.com/s/zqszr3f8y0z7t3c/Admin%20faces%20responsive%20issues.mp4?dl=0

**Comment by rmpestano** [comment]
_From @vishnuragava on September 12, 2018 6:12_

Hi @rmpestano ,
I'm using admin template in my project and I couldn't able to continue further process because it's a major issue for me. So could you please give me the possible solution to fix this issue. 
Thank you.

**Comment by rmpestano** [comment]
Hi @vishnuragava, it has been fixed on master, can you try with admin-template RC19-SNAPSHOT?

You'll need to add snapshots repository on your pom:

```
<repositories>
    <repository>
        <snapshots/>
        <id>snapshots</id>
        <name>libs-snapshot</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by vishnuragava** [comment]
Thank you @rmpestano
