### ISSUE TITLE
Problems with sidebar-menu

### ISSUE THREAD

**Issue by majorgeek85** [adminfaces/admin-template#130]
##### Issue Overview

In RC19/RC18 my sidebar menu is not working as intended. As you can see in the gif, when I press a link in the sidebar the refresh causes the parent menu "Workflow" to appears to remain open but the icon changes from "v" to "<" as if it closed. I have to open and close for it to go back to normal.

##### Current Behaviour

![sidebar](https://user-images.githubusercontent.com/43548458/45966762-f3b65000-c023-11e8-99db-bf42097c6b9f.gif)

##### Expected Behaviour

In RC15 with the same code, when I click in a link the menu remains open and the icon remains "v". I click it next it closes.

##### Additional Information

* AdminFaces version:  1.0.0-RC19-SNAPSHOT
* PrimeFaces version: 
* JSF implementation: 

Please advise if something is missing as it's the first time I submit an issue on github.
Thanks.

**Comment by rmpestano** [comment]
Hi, are you using `data-widget="tree"` on the menu?

```
 <ul class="sidebar-menu tree" data-widget="tree">
```

**Comment by rmpestano** [comment]
Yea, a sample project reproducing the issue would be great

**Comment by rmpestano** [comment]
Hi, do you have any update on the issue?

**Comment by rmpestano** [comment]
Hi, do you have any update on the issue? I'm closing issues without update
