### ISSUE TITLE
IndexOutOfBounds on breadcrumb support

### ISSUE THREAD

**Issue by dquintela** [adminfaces/admin-template#143]
##### Issue Overview

Breadcrumb usage fails when build with urls without extension.
In our use case, we are integrating spring webflow with jsf and adminfaces (though joinfaces)
Throught inspection of source code, we enabled "extension-less-urls" option.

##### Current Behaviour

We get and IndexOutOfBounds exception since were are using webflow paths for bredacrumb construction (ex: /home, /contract/view)

##### Expected Behaviour

The supports doesn't defend against the passing of an already extension-less url. 
Assumes the url may be have been constructed from the view's url...

##### How to reproduce  

.

##### Additional Information

* AdminFaces version:  RC19
* PrimeFaces version: should be irrelevant
* JSF implementation: should be irrelevant

**Comment by rmpestano** [comment]
You should be able to use 1.0.0-RC21-SNAPSHOT, just [configure snapshots](https://github.com/adminfaces/admin-template#snapshots) repo on your pom.xml/build.gradle.
