### ISSUE TITLE
Multi-level menu fail to auto activate when nested on level > 1

### ISSUE THREAD

**Issue by dquintela** [adminfaces/admin-template#145]
##### Issue Overview

Multi-level menu fail to auto activate when nested on level > 1

##### Current Behaviour

Left bar menus are activated (open) on page enter up-to neste level 1. On nest level > 1 the auto open functionality wasn't working.

##### Expected Behaviour

All levels are open.

##### How to reproduce  

Create a multi-level menu as demonstrated on "AdminLTE" (https://adminlte.io/themes/AdminLTE/index2.html)
They fail to maintain open stickness on page reload.

##### Additional Information

* AdminFaces version:  RC19
* PrimeFaces version: should be irrelevant
* JSF implementation: should be irrelevant

**Comment by rmpestano** [comment]
Just added a sample page for multi level menu on showcase, [see here](http://docker175194-env-8309037.jelasticlw.com.br/showcase/pages/components/multilevel.xhtml).

Thank you very much for the contribution!
