### ISSUE TITLE
Problem with primefaces component p:schedule passing from 1.0.0-RC18 to 1.0.0-RC19

### ISSUE THREAD

**Issue by danielemaddaluno** [adminfaces/admin-template#148]
##### Issue Overview

I have a `p:schedule` component in my page which uses a `LazyScheduleModel` like this:

```
@Named
@ViewScoped
public class EventsList implements Serializable {

	private ScheduleModel lazyEventModel;

	@Inject
	LogManager logon;
	
	@Inject
	NightService nightService;

	@Inject
	LocationService locationService;

	private Location selectedLocation;
	private List<Location> locations;

	@PostConstruct
	public void init() {
		locations = locationService.getLocationsFromDatabase(logon.getProvider());

		lazyEventModel = new LazyScheduleModel() {
			@Override
			public void loadEvents(Date start, Date end) {
				DateTime startLdt = CalendarUtils.toDateTime(start);
				DateTime endLdt = CalendarUtils.toDateTime(end);
				List<ScheduleEvent> events = nightService
						.getNightsScheduleEventsByProviderLocationAndDateTimeRange(logon.getProvider(), getSelectedLocation(), startLdt, endLdt);

				for (ScheduleEvent e : events) {
					addEvent(e);
				}
			}
		};
	}
    /* ... */
}
```

And in my page I have a `p:schedule` inside a form like this:

```
<p:schedule id="schedule" value="#{eventsList.lazyEventModel}" draggable="false" resizable="false"/>
```

##### Current Behaviour
From 1.0.0-RC19 and above:

1. the events are not shown on the schedule component and `loadEvents` is never called.

2. I get in the Google Chrome console the following error:
    <img width="1384" alt="screenshot 2019-01-12 00 25 58" src="https://user-images.githubusercontent.com/1886810/51064804-d8d31000-1601-11e9-8719-aaa97e181833.png">
    It is due to the js function `showBar()` from `AdminLTE`, the first time that the `PF('statusDialog')` is called gives me an `Uncaught TypeError: Cannot read property 'show' of undefined`.

Can't say if 1. and 2. are correlated.

##### Additional Information

Testing with `1.0.0-RC18` p:schedule works fine and this problem did not exist.
I tried again recompiling my `ear` with:
- 1.0.0-RC19
- 1.0.0-RC20
- 1.0.0-RC21-SNAPSHOT

And all these 3 have this bug on the `p:schedule` component.

AdminFaces version: admin-template 1.0.0-RC19+
PrimeFaces version: PF 6.2
JSF implementation: Mojarra 2.2.15

**Comment by danielemaddaluno** [comment]
@rmpestano  answering to your previous https://github.com/adminfaces/admin-template/issues/147#issuecomment-453659577
Yes I see exactly the same thing on this page [http://admin-showcase-admin-showcase.7e14.starter-us-west-2.openshiftapps.com/showcase/pages/components/schedule.xhtml#j_idt198:j_idt203](http://admin-showcase-admin-showcase.7e14.starter-us-west-2.openshiftapps.com/showcase/pages/components/schedule.xhtml#j_idt198:j_idt203)
No `ScheduleEvent` at all and on chrome I have that error (event if graphically the schedule component is ok and I can move from a week to another).

**Comment by martinmikula** [comment]
I also found this problem, when i disabled renderAjaxStatus: admin.renderAjaxStatus=false, schedule works as expected, so it seems that statusDialog is not available in time when schedule is trying to get data for first time. Important line from javascript console:
`Widget for var 'statusDialog' not available!
error @ eNp1jFEOAiEMRE-0u__eBqEq2NJaiomJhxd3WU0wfs30zUtFI8HJeSiHdKugj2WLOZWn_NkmwXqOuQyOZ4UfRMIZso0uMTW6bDFsxV8gVIRlL-89NW5ODXS_kO_u2o8jsxVTJzPF3JkLrU9oMDIDEnT2eYsxAFcbtZV_HSpeGbFbL9AMe6s.js.xhtml?ln=omnifaces.combined&v=1547287635000:16415`.

**Comment by danielemaddaluno** [comment]
I noticed that I have this problem on desktop browser:
> Google Chrome (Google Chrome is up to date)
> Version 71.0.3578.98 (Official Build) (64-bit)

And opening the same site with from mobile with Google Chrome for mobile it works fine with any problems.
> Chrome 71.0.3578.99

**Comment by rmpestano** [comment]
Interestingly on desktop the ajaxStatus ([here](https://github.com/adminfaces/admin-template/blob/d30a9419fa0d189284e8dfd772a7716d2cf11c47/src/main/resources/META-INF/resources/admin-base.xhtml#L25) call a dialog to show loading image, [see here](https://github.com/adminfaces/admin-template/blob/d30a9419fa0d189284e8dfd772a7716d2cf11c47/src/main/resources/META-INF/resources/js/admintemplate.js#L267) and [here](https://github.com/adminfaces/admin-template/blob/d30a9419fa0d189284e8dfd772a7716d2cf11c47/src/main/resources/META-INF/resources/admin-base.xhtml#L585).

O mobile the loading dialog is not called so that is probably related with the issue. I hope I can have a look at It.

**Comment by rmpestano** [comment]
Also It is important to not that the [loadding dialog](https://github.com/adminfaces/admin-template/blob/d30a9419fa0d189284e8dfd772a7716d2cf11c47/src/main/resources/META-INF/resources/admin-base.xhtml#L585) was moved to the bottom of the template (to make the page load faster images should be at the bottom) so that is probably the cause.

**Comment by rmpestano** [comment]
Hi again @danielemaddaluno,

As I suspected the issue was caused by loading dialog position on the template. 

Can you try with admin-template 1.0.0-RC21-SNAPSHOT?

Don't forget to clean browser caches. 

Thank you for reporting the issue.

**Comment by danielemaddaluno** [comment]
Yeah! It works fine with the new `1.0.0-RC21-SNAPSHOT`! 🥳
Great job and thank you again @rmpestano
