### ISSUE TITLE
Responsive is not working properly when minimize and maximize the screen and sidebar menu are clickable when dialog is open with dialog modal attribute is true

### ISSUE THREAD

**Issue by vishnuragava** [adminfaces/admin-template#149]
![responive issue](https://user-images.githubusercontent.com/25576826/51070305-11f09c00-1665-11e9-94e6-17966c6b09ec.png)

**Comment by rmpestano** [comment]
Sorry, can't reproduce, need more info.

**Comment by rmpestano** [comment]
Here's what I've tried: https://www.youtube.com/watch?v=bkF9i2Ggrvg&feature=youtu.be

Using adminfaces RC21-SNAPSHOT.

**Comment by vishnuragava** [comment]
Hi can you please provide the work around to fix this issue because we used this template in our project.

**Comment by rmpestano** [comment]
Hi, can you try with latest admin-template (1.0.0-RC21-SNAPHOT) or on showcase here: http://admin-showcase-admin.1d35.starter-us-east-1.openshiftapps.com/showcase/

**Comment by vishnuragava** [comment]
Ok i'll try with latest admin-template snapshot (1.0.0-RC21-SNAPHOT) or on admin-showcase
