### ISSUE TITLE
Make 'content' div a JSF component

### ISSUE THREAD

**Issue by rmpestano** [adminfaces/admin-template#150]
_From @OumalekHD on January 17, 2019 15:0_

Can you please change the [(div id="content")](https://github.com/adminfaces/admin-template/blob/d30a9419fa0d189284e8dfd772a7716d2cf11c47/src/main/resources/META-INF/resources/admin-base.xhtml#L73) element that exist in the admin-template-1.0.0-RC20.jar "admin.xhtml" to support update with primeface JSF component ?

_Copied from original issue: adminfaces/admin-starter#11_

**Comment by rmpestano** [comment]
Hi @OumalekHD, can you try with 1.0.0-RC21-SNAPSHOT?

To use this version you'll need to declare snapshots repository on your pom, s[ee here](https://github.com/adminfaces/admin-template#snapshots).

**Comment by OumalekHD** [comment]
not working because it's the same component in the new snapshots version (div id="content") to correct the problem you should to change the div component to h:outputgroup component
can you please fix that in the next version ?

my needs is to load the xhtml pages by ajax without loading all of contents of website

**Comment by rmpestano** [comment]
Yea, basically what was done on this commit: https://github.com/adminfaces/admin-template/commit/b0604c649e6fcb903e7f9770a80244e44fdef130

Are you sure you're using admin-template 1.0.0-RC21-SNAPSHOT?

**Comment by OumalekHD** [comment]
thank you very much it's working now :) 🥇 👍 
my working pom.xml file :


	<parent>
		<groupId>org.joinfaces</groupId>
		<artifactId>joinfaces-parent</artifactId>
		<version>3.2.6</version>
		<relativePath /> 
	</parent>
	
	<repositories>
	    <repository>
	        <snapshots/>
	        <id>snapshots</id>
	        <name>libs-snapshot</name>
	        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
	    </repository>
	</repositories>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<mojarra.version>2.3.4</mojarra.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.github.adminfaces</groupId>
				<artifactId>admin-template</artifactId>
				<version>1.0.0-RC21-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>com.github.adminfaces</groupId>
				<artifactId>admin-theme</artifactId>
				<version>1.0.0-RC20</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
		</dependency>
		<dependency>
			<groupId>org.joinfaces</groupId>
			<artifactId>adminfaces-spring-boot-starter</artifactId>
			<version>4.0.1</version>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
	</dependencies>
	
	<build>
		<finalName>admin-starter</finalName>
		<resources>
			<resource>
				<filtering>true</filtering>
				<directory>src/main/resources</directory>
			</resource>
			<resource>
				<directory>src/main/docs</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<testResources>
			<testResource>
				<filtering>true</filtering>
				<directory>src/test/resources</directory>
			</testResource>
			<testResource>
				<directory>src/test/java/</directory>
			</testResource>
		</testResources>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by rmpestano** [comment]
:+1:
