### ISSUE TITLE
Issue with sub menus not working

### ISSUE THREAD

**Issue by alaoa** [adminfaces/admin-template#156]
##### Issue Overview

Having problems with the sub menus not working

##### Current Behaviour

I can get the sub menus to work unless i click on the menu search.  They seems to be clashing.  Also I seems to have two of them even though i have it set to false in my config file.
![image](https://user-images.githubusercontent.com/238813/52306795-e6f91f80-2966-11e9-80a2-9786b49952a2.png)

##### Expected Behaviour

An image may worth a thousand words
![image](https://user-images.githubusercontent.com/238813/52306854-07c17500-2967-11e9-9aa6-6fa403a35e69.png)

##### How to reproduce  

So the base project I used was spring-boot-started but then I merged a lot of the showcase code.  I'm using the latest version  even though this was happening in the last

##### Additional Information

* AdminFaces version:  1.0.0-RC21
* PrimeFaces version: 6.2
* JSF implementation:

**Comment by rmpestano** [comment]
Hi, please compare your code with starter project or provide a simple maven project that reproduces the issue.

Looking at the image looks like you are using a newer adminfaces version in an old codebase. Look at the release notes in this project mainly RC15 and later versions

**Comment by alaoa** [comment]
ok thank you so I need the latest version of Admin faces?  I was also getting this message.
2019-02-05 16:49:52.050  WARN 10216 --- [nio-8080-exec-6] j.e.r.webcontainer.jsf.application       : JSF1064: Unable to find or serve resource, fa/font-awesome.css, from library, primefaces.

I'll update the code base and see if that fixes some of the issues.  Thanks again for this great project!!

**Comment by rmpestano** [comment]
I'd suggest you to use the the [SpringBoot archetype](https://github.com/adminfaces/admin-starter-springboot-archetype) and generate a clean project and then port your code to this new project.

About the font-awesome warn you'll need to enable it on web.xml, [see here](https://github.com/adminfaces/admin-starter-springboot/blob/e23e70409924d1a886a834bd8a6c14b52418fdf7/src/main/webapp/WEB-INF/web.xml#L17-L20) for example.

**Comment by alaoa** [comment]
So it look like JSF error happens when i click on a menu.  I added admin.renderMenuSearch=false to only render one menu but i'm thinking it can't load the fontawesome and that might be preventing the menus from working.  

I'm getting this error 
2019-02-07 07:22:38.197  WARN 9020 --- [nio-8080-exec-3] j.e.r.webcontainer.jsf.application       : JSF1064: Unable to find or serve resource, eNpLLi62Ks7IL09OLE7VSy4urgFiq4KizOJcMA_Iyk1NS0xOLbZKzs8tyM9LzSspBskAAIGMFos.css, from library, omnifaces.combined.
2019-02-07 07:22:39.037  WARN 9020 --- [nio-8080-exec-3] j.e.r.webcontainer.jsf.application       : 

org.apache.catalina.connector.ClientAbortException: java.io.IOException: An established connection was aborted by the software in your host machine

**Comment by alaoa** [comment]
Ok I'm closing this issues.  The fix was simple in the top of the menu.xhtml made the following update.

`<ul class="sidebar-menu" data-widget="tree">`

`<ul class="sidebar-menu" > `
