### ISSUE TITLE
Weird url when I run my app

### ISSUE THREAD

**Issue by solokingjec** [adminfaces/admin-template#160]
When I run my app, the url is not properly formed.
This is my admin configuration 

admin.indexPage=login.htm
admin.renderMessages=false
.....

when I run, it gives the url like this

http://localhost:8080/http:/login.htm

Instead of 

http://localhost:8080/login.htm

I can add you on bit-bucket.

* AdminFaces version:  1.0.0-RC22-SNAPSHOT
* PrimeFaces version: 6.2
* JSF implementation: 2.2

**Comment by rmpestano** [comment]
Hi, how's the url mapping of faces servlet in web.xml?

**Comment by rmpestano** [comment]
Does it work with RC20?

**Comment by solokingjec** [comment]
With RC20 its working perfect.

The url mapping looks like this
<servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.htm</url-pattern>
    </servlet-mapping>

Best Regards
Francis Njoroge Mwariri
P.O. Box 63-01028 Gatukuyu,Kenya.
Email:email2mefrancis@gmail.com
Whatsap: +254788647116
java enterprise application developer at mobsofts company

**Comment by rmpestano** [comment]
It's probably [related to this](https://github.com/adminfaces/admin-template/issues/147#issuecomment-453122872).

I'll do some tests here.

**Comment by rmpestano** [comment]
You can't have a login and index (initial page) page on your application? For example this works for me:

```
admin.loginPage=login.htm
admin.indexPage=index.htm
```
