### ISSUE TITLE
Navigation Issue

### ISSUE THREAD

**Issue by muhdkhokhar** [adminfaces/admin-template#163]
When I run the application I et this error

Could not resolve NavigationCase for outcome: /index.xhtml

**Comment by rmpestano** [comment]
Hi there, can you reproduce on [admin-starter](https://github.com/adminfaces/admin-starter)? If not can you provide a sample project that reproduces the issue?

**Comment by muhdkhokhar** [comment]
Yes I am able to do that. I have foudn solution as well. If you use multi-module then put the the sources under

src/main/resources/META-INF.resources

It works now
