### ISSUE TITLE
Active menu item selection does not work when application at context path

### ISSUE THREAD

**Issue by flynnk** [adminfaces/admin-template#164]
The active menu item option auto selection based on URL does not work when the application is deployed at a context path.

In this code:

/* set active style in menu based on current url */
function activateMenu(url, activated) {
    var activePage = stripTrailingSlash(url);
    $('.sidebar-menu li a, ul.navbar-nav li a').each(function () {
        var currentPage = stripTrailingSlash($(this).attr('href'));
        //console.log("activePage:" + activePage +" currentPage:" + currentPage);
        if (activePage == currentPage) {
            $(this).parent().addClass('active');
            activated = true;
        } else {
            $(this).parent().removeClass('active');
        }
    });
}

activePage is equal to /context/index.jsf while currentPgae is index.jsf.  The page is never found, and no item is marked as active.

* AdminFaces version:  RC21
* PrimeFaces version: 6.2
* JSF implementation: Wildfly 16 (JSF 2.3)

**Comment by flynnk** [comment]
This does work if the path for the link in the menu item is specified like this:

```xml
<p:link href="/config.jsf">
  <i class="fa fa-cog"/>
  <span>Settings</span>
</p:link>
```

but not like this:

```xml
<p:link href="config.jsf">
  <i class="fa fa-cog"/>
  <span>Settings</span>
</p:link>
```

**Comment by rmpestano** [comment]
Hi @flynnk, 

You should use **outcome** instead of href otherwise you'll have problems when migratória to PrimeFaces 7.x. because It Will not append application context anymore (when using href)

You see the same issue when using the outcome ?

**Comment by flynnk** [comment]
Hello!  BTW, loving the library.  It's so nice to have the theme for Primefaces that makes everything look modern and professional, and the template is also great at providing a good starting place for business applications.

I've actually already switched to outcomes, using /config for example.  I had just started with this example:

https://adminfaces.github.io/site/docs/latest/#example

and that's still on hrefs.  I'm also having trouble with the clearBreadCrumbs() function from that example, but that is unrelated to this issue.

A few notes in the documentation on the proper design of the menu would probably be helpful--it took me a couple of hours to work through this issue.

**Comment by rmpestano** [comment]
Hi, glad you are enjoying the project!

I'll update the example, thanks for pointing out.

Note that the starter projects should have the working code, [see here](https://github.com/adminfaces/admin-starter/blob/master/src/main/webapp/includes/menu.xhtml).

About the clearBreadCrumb It would be nice If you could open a separed issue with details.

Thanks for the feedbacks!
