### ISSUE TITLE
Unable to find or serve resource, theme.css, from library, primefaces-admin

### ISSUE THREAD

**Issue by mnesarco** [adminfaces/admin-template#174]
##### Issue Overview

After upgrate to 1.0.0 I got this warning:
Unable to find or serve resource, theme.css, from library, primefaces-admin

The app works but I am not sure if this will generate problems later.

##### How to reproduce  

upgrade from 1.0.0-RC21 to 1.0.0

##### Additional Information

* AdminFaces version:  1.0.0
* PrimeFaces version: 7.0
* JSF implementation: Mojarra (Wildfly AS)

**Comment by rmpestano** [comment]
Hi, sometimes I see this error when I'm running the application from the IDE, on eclipse it is usually a `deploymentAssembly` configuration issue.

If you  build the application with maven/gradle and deploy on the server you see the same error?

**Comment by mnesarco** [comment]
Hi, after deployed the .war directly to wildfly, I see this warning on every navigation:

```
2019-03-29 13:30:07,036 WARNING [javax.enterprise.resource.webcontainer.jsf.application] (default task-58) JSF1064: Unable to find or serve resource, eNp1ikEOwzAIBF_k5J7fUJdEtsAQwIdIfXyr2qdUPe3u7KgVxh0y-lbPjnatI5bqL_3zJaV-lOY3J4vhD2KVhi2-bvUVuonBGNtDJDwMdOHSJoPnpycKvLNAVoLAyZwKezYhmuIbwM9P7g.js, from library, omnifaces.combined.
2019-03-29 13:30:07,036 WARNING [javax.enterprise.resource.webcontainer.jsf.application] (default task-58) : java.io.IOException: Broken pipe
```

The app works, apparently without problems. but... it looks like something is not ok, or maybe I need to change some special configuration for 1.0.0?

**Comment by rmpestano** [comment]
There is no need to change anything if you were using RC21.

The warning is specific from OmniFaces resource handler, I don't think it has any impact. 

You see any javascript errors on the browser console?

**Comment by mnesarco** [comment]
No javascript errors.
So I suppose I can ignore those warnings by now. Everything seems to work anyway.

Thanks.

**Comment by rmpestano** [comment]
Great, I'll close the issue and any related problems you can reopen.
