### ISSUE TITLE
primefaces 7.0 issues with dependent selectOneMenus

### ISSUE THREAD

**Issue by anumber8** [adminfaces/admin-template#175]
##### Issue Overview

Hello,

I've upgraded to the latest version of this template , 1.0.0, which brings in primefaces 7.0
and created a page with two selectonemenu where the selection of an item of one trigger the update by ajax of the contents of the second. what happend is that when i select the first one de results on the second appears on the left corner instead of the right position of the component which is in the content area by the right side. degrading to version 1.0.0-RC21 this issue doesn't happend.

##### Current Behaviour

An image may worth a thousand words

![wrong behaviour](https://user-images.githubusercontent.com/18664305/56299162-c520d380-6133-11e9-9387-e160e60f0d2f.png)

##### Expected Behaviour
![correct behaviour](https://user-images.githubusercontent.com/18664305/56297514-bdabfb00-6130-11e9-9897-aff369d4d076.png)

An image may worth a thousand words

##### How to reproduce  

`<div>
	<div class="form-group col-md-3">
								<p:outputLabel for="provincia" value="Província:" />
								<p:selectOneMenu id="provincia" converter="provinciaConverter"
									value="#{armazemListController.filter.entity.endereco.provincia}">
									<f:selectItem itemLabel="Escolha Aqui" itemValue="#{null}" />
									<f:selectItems
										value="#{formController.findAllProvincia()}"
										var="_provincia" itemLabel="#{_provincia.nome}"
										itemValue="#{_provincia}" />
									<p:ajax event="itemSelect" update="distrito" />
								</p:selectOneMenu>
							</div>`

							<div class="form-group col-md-3">
								<p:outputLabel for="distrito" value="Distrito:" />
								<p:selectOneMenu id="distrito" converter="distritoConverter"
									value="#{listController.filter.entity.endereco.distrito}">
									<f:selectItem itemLabel="Escolha Aqui" itemValue="#{null}" />
									<f:selectItems
										value="#{listController.findDistritoByProvinciaId()}"
										var="_distrito" itemLabel="#{_distrito.nome}"
										itemValue="#{_distrito}" />
								</p:selectOneMenu>
							</div>
						</div>`

##### Additional Information

* AdminFaces version:  1.0.0
* PrimeFaces version: 7.0
* JSF implementation: 2.3

**Comment by rmpestano** [comment]
Hi, downgrading PrimeFaces to 6.2 (and keeping admin-template 1.0.0) solves the issue? 

Canal you reproduce on admin-starter project?

**Comment by anumber8** [comment]
I will try to reproduce it on admin-starter, and post it asap.

**Comment by rmpestano** [comment]
Also, make sure you have clean browser caches when testing two different versions of theme and primefaces.

**Comment by rmpestano** [comment]
Hi again @anumber8,

I've created a branch on admin-starter to reproduce this issue but it worked for me:

![nested-selects](https://user-images.githubusercontent.com/1592273/56449536-f692ce00-62f0-11e9-8776-8f9e12ec574a.png)

the [code is here](https://github.com/adminfaces/admin-starter/blob/538543a7a010d6309707c8a81c5c5597c208e8d0/src/main/webapp/index.xhtml#L27-L54), can you have a look and try to reproduce?

**Comment by rmpestano** [comment]
Alright just reproduced by deploying on a JavaEE 8 server (Wildfly 15.0.1):

![Screenshot from 2019-04-19 22-22-36](https://user-images.githubusercontent.com/1592273/56449594-fd6e1080-62f1-11e9-9b0a-ebb16507660f.png)

To fix just upgrade **OmniFaces to version 3.2**

```
<dependency>
            <groupId>org.omnifaces</groupId>
            <artifactId>omnifaces</artifactId>
            <version>3.2</version>
        </dependency>    
```

Let me know if it solves the problem for you too.

**Comment by anumber8** [comment]
Hi @rmpestano thank you once again.
I did follow your suggestion and upgraded the Omnifaces to 3.2 and it did solve the issue and running on thorntail 2.4.0.

**Comment by rmpestano** [comment]
That's great! closing the issue, thank you for  the feedback.
