### ISSUE TITLE
Support OWB in Tomcat

### ISSUE THREAD

**Issue by skybber** [adminfaces/admin-template#178]
Our tech stack is based on OWB. OWB doesn't support @Inject in @WebFilter (AdminFilter). But it is possible to use `CDI.getCurrent().getBeanManager()...` or Omnifaces's `Beans.getReference(SomeBean.class);` instead of @Inject to support OWB as well.

**Comment by rmpestano** [comment]
Hi @skybber,

which version of OWB are you using? 

We have ft tests that runs on Tomee 1.7 (and 7.x) which uses OWB so Im sure it works but maybe you're using an older version. 

If we use `CDI.getCurrent()` we'll break JavaEE 6 support

**Comment by skybber** [comment]
We're testing it on Tomcat, pby Tomee is ok.

**Comment by rmpestano** [comment]
I'll try to make [admin-starter-tomcat](https://github.com/adminfaces/admin-starter-tomcat) work with OWB over this weekend.

Thank you for the feedback.

**Comment by skybber** [comment]
thanks for great product!

**Comment by rmpestano** [comment]
Hi @skybber,

can you try with admin-template 1.0.1-SNAPSHOT?

You'll need to declare [snapshots repository](https://github.com/adminfaces/admin-template#snapshots) on your pom.xml.

**Comment by rmpestano** [comment]
Just released v1.0.1, any problem releated with this issue, please reopen.

**Comment by skybber** [comment]
Thanks. it's working now.
