### ISSUE TITLE
sidebar-menu tree hide search bar

### ISSUE THREAD

**Issue by tulkas85** [adminfaces/admin-template#186]
I don't want search bar in sidebar-menu.

I try put this in footer of template.xhtml

$('.sidebar-form').hide();

It works, but there is a better way to do this ?

thank you

    AdminFaces version: 4.0.0
    PrimeFaces version: 7.0
    JSF implementation:

**Comment by rmpestano** [comment]
Yes, use `admin.hideSearchMenu=true` configuration, for details see here: https://adminfaces.github.io/docs/latest/#configuration

**Comment by tulkas85** [comment]
It works.
Thank you !
