### ISSUE TITLE
ToggleSidebar não mantem estado

### ISSUE THREAD

**Issue by CarlosEReis** [adminfaces/admin-template#188]
Sidebar não mantém estado entre a navegação das páginas, ou seja,
uma vez que **escondo** a sidebar a página **A** ao ir para página **B** ela volta ao estado normal.

Existe alguma configuração que faça com a sidebar só altere o estado com a intervenção do usuário?

**Comment by rmpestano** [comment]
Ola @CarlosEReis,

tentou usar a propriedade `admin.controlSidebar.sidebarCollapsed=true` no arquivo `src/main/resources/admin-config.properties`?
