### ISSUE TITLE
Twice header of <p:dataTable> with scrollable option

### ISSUE THREAD

**Issue by hir0ku** [adminfaces/admin-template#191]
##### Issue Overview

Twice header of <p:dataTable> with scrollable option.
![table_double_header](https://user-images.githubusercontent.com/57468638/68357524-fce77b00-0158-11ea-8536-5e2e2a12002a.png)

##### Current Behaviour
- 2 header is in top of the table with scrollable option.

##### Expected Behaviour
- only one header is in top of the table with scrollable option.

##### How to reproduce  
```
<p:panel header="table test">
    <p:dataTable value="#{indexView.tableItemDtoList}" var="item" scrollable="true" scrollHeight="300">
        <p:column headerText="word0">
            <h:outputText value="#{item.word0}"/>
        </p:column>
        <p:column headerText="word1">
            <h:outputText value="#{item.word1}"/>
        </p:column>
        <p:column headerText="number1">
            <h:outputText value="#{item.number1}"/>
        </p:column>
        <p:column headerText="number2">
            <h:outputText value="#{item.number2}"/>
        </p:column>
    </p:dataTable>
</p:panel>
```

entire code is here. https://github.com/hir0ku/adminfaces-operation-verification/blob/master/src/main/webapp/index.xhtml

##### Additional Information

* AdminFaces version:  1.0.0
  * also try 1.0.2, same problem.
* PrimeFaces version: 7.0
* JSF implementation: Wildfly 16.0.0.Final Mojarra 2.3.9.SP01

**Comment by rmpestano** [comment]
It was just fixed and the fix will be available in adminfaces `1.3.0` to be released today. Thank you for your feedback!
