### ISSUE TITLE
Error FileUpload

### ISSUE THREAD

**Issue by renanccortes** [adminfaces/admin-template#204]
Hello, I'm having problems using fileupload using admin-template 1.3.0, is there any configuration needed to run?
  

* AdminFaces version 1.3.0:  
* PrimeFaces version 10.0.0:

**Comment by xexes** [comment]
there is syntax error in the admintemplate.js method "windowResize()", maybe this breaks the execution of further javascript

**Comment by rmpestano** [comment]
Hi guys, that should be fixes in latest version (`1.4.0`), let me know if that's the case.

**Comment by renanccortes** [comment]
Thanks Rafa!
