### ISSUE TITLE
syncax error in filea admintemplate.js

### ISSUE THREAD

**Issue by xexes** [adminfaces/admin-template#205]
##### Issue Overview

syntac error in file  admintemplate.js
function windowResize() {
    if(!isMobile() && )
    setTimeout(function () {
        $(window).trigger('resize');
    }, 500);
}

* AdminFaces version: 1.  3

**Comment by rmpestano** [comment]
Hi @xexes, can you try with `v1.4.0`? Let me know if the issue persists
