### ISSUE TITLE
Provide a Jakarta EE 9 version

### ISSUE THREAD

**Issue by vitorsouza** [adminfaces/admin-template#206]
##### Issue Overview

Latest version of Admin Template references Java EE `javax.` APIs, thus not working in a Jakarta EE 9 setting.

##### Current Behaviour

If you start a new Web project, use `jakarta.jakartaee-web-api` 9.1 as a dependency together with `admin-template` 1.3.1 and deploy it on a Jakarta EE 9 server (e.g., WildFly 25.0.1 Preview EE 9.1) you get a `NoClassDefFound` exception, as `admin-template` will reference Jave EE 9 classes under `javax.` and the Jakarta EE 9 server will provide these classes under a new package naming structure `jakarta.`.

##### Expected Behaviour

Admin Template could provide a _Jakarta EE 9 version_ of the dependency, the same way PrimeFaces 10 does, using classifiers:

```xml
    <dependency>
      <groupId>org.primefaces</groupId>
      <artifactId>primefaces</artifactId>
      <version>10.0.0</version>
      <classifier>jakarta</classifier>
    </dependency>  
```

By adding the `jakarta` classifier, Maven would download a version of `admin-template` that has been built for Jakarta EE 9.

##### How to reproduce  

I created an [AdminFaces in Jakarta EE 9 Starter Project](https://github.com/dwws-ufes/admin-starter-jee9) after performing the following:

1. [Cloned the admin-template repository](https://github.com/vitorsouza/admin-template);
2. [Upgraded Java EE references to Jakarta EE 9 references](https://github.com/vitorsouza/admin-template/commit/840cdeaae78f4ee6042fdd52b7d4b7e3af63405c);
3. Ran `mvn deploy` to create the new artifact at a local [Maven](https://maven.apache.org/) repository;
4. Then uploaded it to [LabES UFES' webserver](https://labes.inf.ufes.br/maven2/com/github/adminfaces/admin-template/1.3.1-jakarta/admin-template-1.3.1-jakarta.pom) in order for people to be able to declare it as a dependency in their Maven projects;
5. Created the [admin-starter-jee9](https://github.com/dwws-ufes/admin-starter-jee9) project as an example of use.

If you deploy the [admin-starter-jee9](https://github.com/dwws-ufes/admin-starter-jee9) project in a Jakarta EE 9 server you will get the expected behavior. To get the current behavior, modify the project's `pom.xml` to reference version 1.3.0 of `admin-template` instead of the 1.3.1-jakarta version I created.

##### Additional Information

* AdminFaces version: 1.3.1
* PrimeFaces version: 10.0
* JSF implementation: Mojarra 3.0.0.SP04 under WIldFly 25.0.1 Preview EE 9.1

**Comment by rmpestano** [comment]
Hi @vitorsouza, starting from `v1.4.0` adminfaces will be only compatible with jakarta ee package. 

If needed we can create a `legacy` classifier to support `javax` package, please create an issue if that's the case.

Thank you!

**Comment by vitorsouza** [comment]
> Hi @vitorsouza, starting from `v1.4.0` adminfaces will be only compatible with jakarta ee package.

Did this not go through? It seems that changes were made in branch [206-jakartaee-migration](https://github.com/adminfaces/admin-template/tree/206-jakartaee-migration) but never merged into master. I tried using [admin-template-1.5.1 from mvnrepository](https://mvnrepository.com/artifact/com.github.adminfaces/admin-template) but it seems to be using javax. packaging still.

**Comment by rmpestano** [comment]
Hey @vitorsouza, you're right. I'll try to release a new version today. 

Thanks for the heads up!

**Comment by rmpestano** [comment]
Hey @vitorsouza, I've just released v`1.6.0` and now it should be ok. 

I've migrated [Admin starter to jakarta](https://github.com/adminfaces/admin-starter/commit/dda0a159fe9d604cbccecb9beab2b60f958569d0) and it seems to be working on wildfly 26.1.1. 

For the javax support I tested the [quarkus-admin-starter](https://github.com/adminfaces/quarkus-admin-starter/blob/fa651c30408fdd6d941d1c6546746ea1b10031a7/pom.xml#L43-L58) and it's also working.

Thank you again and sorry for the issues in previous releases.

**Comment by vitorsouza** [comment]
Thank you for working on this! Tried version 1.6.1 from mvnrepository and it works great. Thanks again!

**Comment by rmpestano** [comment]
Thank you for the update @vitorsouza!

**Comment by anumber8** [comment]
Hi @rmpestano hope you are doing well. Congratulations adminfaces its an awesome piece of work.
Are you planning to migrate to primefaces 11 this year?
Keep up the good work, cheers!!
