### ISSUE TITLE
Web session cluster is not working

### ISSUE THREAD

**Issue by Mamezou-zhang-yong** [adminfaces/admin-template#209]
##### Issue Overview
when I try to use web session cluster with admin-template via ` <distributable />`,  I got the following warn, and the distributable setting was disabled.
` WARN  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0081: The deployment sessiontest.war will not be distributable because this feature is disabled in web-fragment.xml of the module admin-template-1.3.2.jar.`

##### Current Behaviour

the ` <distributable />`  was overrided.

##### Expected Behaviour

 `<distributable />`  should be kept

##### How to reproduce  

add `<distributable />` into web-fragment.xml

https://github.com/melloware/primefaces/commit/0015d7d2d95cab167207e4f2b83eaeba182fc939

##### Additional Information

* AdminFaces version:  1.3.2
* PrimeFaces version: 11
* JSF implementation:

**Comment by Mamezou-zhang-yong** [comment]
this issue affects `admin-theme`

**Comment by rmpestano** [comment]
Thanks @Mamezou-zhang-yong!
