### ISSUE TITLE
Consider different branch for "jakarta" and "javax" releases

### ISSUE THREAD

**Issue by persapiens** [adminfaces/admin-template#218]
##### Issue Overview

   Admin Template uses the main branch to create **Jakarta** and **Javax** releases. It resulted in some management problems like #216 and #211.

##### Current Behaviour

  A single branch manages Jakarta and Javax releases. Today, it eases the coding task. However, the release process of Admin Template is challenging to manage: maven release is manual, and it releases only javadoc and source code for Jakarta, missing Javax javadoc and source code jars.

##### Proposed Behaviour

  You could let your **main** branch as Jakarta one. 
  I propose to create a Javax branch.
  If you have two branches, Jakarta (main) and Javax, you can:
  - manage and evolve Jakarta and Javax source code independently.
  - release the two branches quickly.
  - deprecate Javax branch easily in the future;
  - have faces-config.xml, web-fragment.xml, and admin-taglib.xml using different prefixes according to Jakarta and Javax specifications;

##### Additional Information

* AdminFaces version:  1.6.1

**Comment by rmpestano** [comment]
Hey @persapiens, decided to drop javax support ( #219), closing this one.
