### ISSUE TITLE
Buttons with icons have too much right padding

### ISSUE THREAD

**Issue by trajano** [adminfaces/admin-template#26]
##### Issue Overview

Tell us briefly what the problem is about.

##### Current Behaviour

![image](https://user-images.githubusercontent.com/110627/28418511-f75cc674-6d29-11e7-8c1b-0875c55533b2.png)

![image](https://user-images.githubusercontent.com/110627/28418524-053a1e90-6d2a-11e7-9589-54c49facfeff.png)

##### Expected Behaviour

Less padding

##### How to reproduce  

https://github.com/adminfaces/admin-starter/blob/master/src/main/webapp/car-form.xhtml#L25

```html
                        <p:commandButton value="Save" action="#{carFormMB.save}" update="@form"
                                         icon="fa fa-check" styleClass="btn-primary"/>
                        <p:spacer width="5" rendered="#{carFormMB.isNew()}"/>
                        <p:commandButton value="Clear" action="#{carFormMB.clear}" process="@this"
                                         icon="fa fa-refresh" styleClass="btn-success"
update="@form" rendered="#{carFormMB.isNew()}" resetValues="true"/>```

**Comment by rmpestano** [comment]
Hi @trajano,

sorry I didn't got the issue, do you have an image with the "less padding" you want?

 I think what is important is that the text is centralized.

**Comment by trajano** [comment]
Here's an image I manipulated the DOM on the browser
![image](https://user-images.githubusercontent.com/110627/28463929-f32f8286-6df0-11e7-995c-16c5c934fcd6.png)

**Comment by rmpestano** [comment]
Hi @trajano,

you can change that you a css rule like below:

```
body .button.ui-button-text-icon-left .ui-button-text {
    padding-right: 0.8em;
}
``` 

does it help?

**Comment by rmpestano** [comment]
To find the rule you need to override just right-click on the element and inspect it, then find the rule and make it more specific (on the example above I've put a 'body' selector) in order to override it:

![css-rule](https://user-images.githubusercontent.com/1592273/28464261-c080351a-6dfa-11e7-9c58-410653a24dcf.png)
