### ISSUE TITLE
OneMenu hover seems tot be not working

### ISSUE THREAD

**Issue by asbachb** [adminfaces/admin-template#27]
##### Issue Overview

Mouse hover over oneMenu items not visually shown.

##### Current Behaviour

When hover with your mouse over an oneMenu the entry is not highlighted.

##### Expected Behaviour

When hover with your mouse over an oneMenu the entry should be highlighted.

reference https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml

##### How to reproduce  

https://adminfaces-rpestano.rhcloud.com/showcase/pages/form/forms.xhtml

see https://webmshare.com/1MoqV

##### Additional Information

* Affected version: 1.0.0-RC9
* Browser version: Tested with Chrome 60.0.3112.78 and Firefox 54.0.1

**Comment by rmpestano** [comment]
Hi @asbachb,

this is a design decision, note that not all primefaces themes uses hover effect on select one, see [primefaces ultima sample page here](https://www.primefaces.org/ultima/sample.xhtml).  

However you can add the hover easily using following css rule:

```
ui-selectonemenu .ui-selectonemenu-trigger.ui-state-hover {

	background-color: #eeeeee!important;

}
```

Thank you for your feedback!

**Comment by asbachb** [comment]
Ah sorry. Didn't got that. Thanks for your feedback!
