### ISSUE TITLE
Allow customize header and sidebar using admin-template

### ISSUE THREAD

**Issue by jandrei** [adminfaces/admin-template#38]
##### Issue Overview

I need customize header and sidebar or remove that in same pages.

##### Current Behaviour

Today admin-template let insert code before and after but not replace all code of menu and sidebar.

##### Expected Behaviour

I expected remove thats parts and insert any other code to customize.

##### Additional Information

* Affected version: 1.0.0-RC11

**Comment by rmpestano** [comment]
Hi @jandrei,

don't you think we can do what you propose in PR #36 using pure css? ex:

```
  <style>
            #loader {
                display: none;
            }
            
            .main-header {
                display: none;
            }
        </style>
```

Or are you thinking in something else?

We also have to becareful because if we hide the header we main get javascript errors because admin-lte uses javascript to control when header is visibled or not (based on user display resolution).

**Comment by rmpestano** [comment]
I've tested above css and the only issue I saw is that there is a black area on top of left menu. But maybe it will be filled with your custom menu implementation, look:

![hide-header](https://user-images.githubusercontent.com/1592273/34910663-20f92920-f8a1-11e7-8eb0-e4c76aee6a90.png)

**Comment by jandrei** [comment]
Now i understand the danger of make that change int the template, but i wish could make this possible, i go study better before try other PR.
I see in js the local with this responsability, but I I would like do this for remove code unecessary into html.

**Comment by rmpestano** [comment]
No problem, you can actually keep the PR open If you think you can evolve the Idea.

**Comment by jandrei** [comment]
Ok, thank you.

**Comment by jandrei** [comment]
Closing because it is dangerous to template, and i dont have sure i have succeed making this.
