### ISSUE TITLE
Working with shiro filter

### ISSUE THREAD

**Issue by solokingjec** [adminfaces/admin-template#39]
I am trying the template. It seems to be a promising thing. I am stuck on how to make it work with shiro filter which is already configured. I want authorisation with roles. If it can work without shiro its okay as long as I can allow designated pages according to roles without configuring anything on the sever

**Comment by solokingjec** [comment]
https://shiro.apache.org this is the shiro project am using for security

**Comment by rmpestano** [comment]
@solokingjec,

can you share the project which uses shiro and admin template? 

What issues are you facing?

**Comment by rmpestano** [comment]
Hi again,

I've added a shiro example here: https://github.com/adminfaces/admin-starter-shiro

can you try it?

**Comment by solokingjec** [comment]
Thankyou so much. I will try it and give a feed back

Best Regards
Francis Njoroge Mwariri
P.O. Box 63-01028 Gatukuyu,Kenya.
Email:email2mefrancis@gmail.com
Whatsap: +254788647116
Facebook:solo King Jec Javanese
java enterprise application developer at mobsofts company

**Comment by solokingjec** [comment]
Hello. I fixed my project and it looks good now. Is it possible to add the
company title on the top bar?


Best Regards
Francis Njoroge Mwariri
P.O. Box 63-01028 Gatukuyu,Kenya.
Email:email2mefrancis@gmail.com
Whatsap: +254788647116
Facebook:solo King Jec Javanese
java enterprise application developer at mobsofts company

**Comment by rmpestano** [comment]
Hi @solokingjec,

can you open another issue with details? An image showing the position you'd like the title would be great.

**Comment by solokingjec** [comment]
@rmpestano please see this https://github.com/adminfaces/admin-template/issues/40 thanks.
