### ISSUE TITLE
Adding Organisation name on the top bar.

### ISSUE THREAD

**Issue by solokingjec** [adminfaces/admin-template#40]
Is it possible to add the title as shown in the image
![screenshot from 2018-02-16 16-06-52](https://user-images.githubusercontent.com/6312641/36309132-721e2bc2-1334-11e8-9fda-d94dd28fc717.png)

**Comment by rmpestano** [comment]
Hi @solokingjec,

I've had a look and didn't found an easy way to do that. Mainly because top bar menu is using floating divs (on the left the hamburger menu and on the right the user details) and there's no easy way to centralize this without changing the template structure, [see here](https://stackoverflow.com/questions/1232096/how-to-horizontally-center-a-floating-element-of-a-variable-width). 

I have made some progress but it breaks other things, mainly when you are on small screens and the menus are collapsed.

**Comment by rmpestano** [comment]
Hi again,

Next version will have support for centralized title in top bar, just add

```
 <ui:define name="center-header">
   Your Title here
</ui:define>
```

To your template or page.

I've added an [example here](http://admin-showcase-admin-showcase.7e14.starter-us-west-2.openshiftapps.com/showcase/pages/layout/menu.xhtml) 

![center-menu](https://user-images.githubusercontent.com/1592273/36403906-8c1923d0-15c6-11e8-9cde-b859295b7242.png)


To use this now you need to use admin-template and admin-theme 1.0.0-RC13-SNAPSHOT:

```
<dependency>
    <groupId>com.github.adminfaces</groupId>
    <artifactId>admin-template</artifactId>
    <version>1.0.0-RC13-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>com.github.adminfaces</groupId>
    <artifactId>admin-theme</artifactId>
    <version>1.0.0-RC13-SNAPSHOT</version>
</dependency>
```

You'll also need to add ```snapshots``` repository:

```
 <repositories>
        <repository>
            <snapshots/>
            <id>snapshots</id>
            <name>libs-snapshot</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>

**Comment by solokingjec** [comment]
The example you have sent is using primefaces 6.2.RC2. Also when I change
the versions for admin-templates, the application does not run again. Am
getting an error that the page is not responding properly.

Best Regards
Francis Njoroge Mwariri
P.O. Box 63-01028 Gatukuyu,Kenya.
Email:email2mefrancis@gmail.com
Whatsap: +254788647116
Facebook:solo King Jec Javanese
java enterprise application developer at mobsofts company

**Comment by rmpestano** [comment]
Can you share an example application or the error stacktrace? Otherwise I will not be able to help. 

Also note that this feature is not tied to any PrimeFaces version, the example I've share was just to show the usage.

**Comment by solokingjec** [comment]
![screenshot from 2018-03-28 15-48-33](https://user-images.githubusercontent.com/6312641/38029934-e09163aa-329f-11e8-9668-14f771ed2f2c.png)
![screenshot from 2018-03-28 15-48-53](https://user-images.githubusercontent.com/6312641/38029935-e10f09cc-329f-11e8-804a-9f98de680142.png)
![screenshot from 2018-03-28 15-49-12](https://user-images.githubusercontent.com/6312641/38029936-e1d590c4-329f-11e8-8b32-3a5d0805323f.png)

**Comment by rmpestano** [comment]
Hi,

your dependencies looks ok, your problem should be something else. 

How's your `web.xml` and `admin-config.properties`?

**Comment by solokingjec** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="3.1" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd">
    <context-param>
        <param-name>javax.faces.PROJECT_STAGE</param-name>
        <param-value>Development</param-value>
    </context-param>
    <context-param>
        <param-name>primefaces.THEME</param-name>
        <param-value>admin</param-value>
    </context-param>
    <context-param>
        <param-name>primefaces.FONT_AWESOME</param-name>
        <param-value>true</param-value>
    </context-param>
    <context-param>
        <param-name>javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL</param-name>
        <param-value>true</param-value>
    </context-param>
    <servlet>
        <servlet-name>Faces Servlet</servlet-name>
        <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.htm</url-pattern>
    </servlet-mapping>
    <listener>
        <listener-class>org.apache.shiro.web.env.EnvironmentLoaderListener</listener-class>
    </listener>

    <filter>
        <filter-name>ShiroFilter</filter-name>
        <filter-class>org.apache.shiro.web.servlet.ShiroFilter</filter-class>
    </filter>

    <filter-mapping>
        <filter-name>ShiroFilter</filter-name>
        <url-pattern>/*</url-pattern>
        <dispatcher>REQUEST</dispatcher> 
        <dispatcher>FORWARD</dispatcher> 
        <dispatcher>INCLUDE</dispatcher> 
        <dispatcher>ERROR</dispatcher>
    </filter-mapping>
</web-app>

**Comment by solokingjec** [comment]
admin.templatePath=/WEB-INF/templates/template.xhtml

admin.loginPage=login.htm
admin.indexPage=login.htm
admin.dateFormat=MM/dd/yyyy HH:mm:ss
admin.templatePath=admin.xhtml
admin.breadcrumbSize=5
admin.renderMessages=false
admin.renderAjaxStatus=false
admin.disableFilter=false
admin.renderBreadCrumb=true
admin.enableSlideMenu=true
admin.enableRipple=true
admin.rippleElements= .ripplelink,button.ui-button,.ui-selectlistbox-item,.ui-multiselectlistbox-item,.ui-selectonemenu-label,.ui-selectcheckboxmenu,\
.ui-autocomplete-dropdown, .ui-autocomplete-item ... (the list goes on)
admin.skin=skin-blue 
admin.autoShowNavbar=true 
admin.ignoredResources=

**Comment by solokingjec** [comment]
![screenshot from 2018-03-28 17-49-14](https://user-images.githubusercontent.com/6312641/38036864-5c3c32fe-32b0-11e8-87fa-8da092c0f8f7.png)

**Comment by solokingjec** [comment]
When I test the starter project, Its working fine with the dependencies. The error is only happening when I change the dependencies

**Comment by solokingjec** [comment]
I can pm you the project link

**Comment by rmpestano** [comment]
Hi, just zip It and attach here or send to my e-mail.

**Comment by solokingjec** [comment]
Please give me your email.


Best Regards
Francis Njoroge Mwariri
P.O. Box 63-01028 Gatukuyu,Kenya.
Email:email2mefrancis@gmail.com
Whatsap: +254788647116
Facebook:solo King Jec Javanese
java enterprise application developer at mobsofts company
