### ISSUE TITLE
Support rendering breadcrumb title from page title

### ISSUE THREAD

**Issue by torgre** [adminfaces/admin-template#50]
##### Issue Overview

It would be great to minimize the effort for creating breadcrumbs if the title of the page equals the title of the breadcrumb and the title is not a complex mixture of HTML elements.

##### Current Behaviour

Specify the title of the page using `<ui:define name="title">My title</ui:define>` and specify the title of the breadcrumb via `<adm:breadcrumb title="My title" />`.

##### Expected Behaviour

Specify the title of the page using a generic param `<ui:param name="title" value="My title" />` that is both used for the page title and the breadcrumb title.

This should be configurable using an admin configuration.

**Comment by rmpestano** [comment]
Hi @torgre, nice idea, I've just added a comment on the PR. If I understod the idea I think we can implement it without the config property.

**Comment by torgre** [comment]
Regardless of having it a configuration or not (as discussed in the PR), I am now using something like

```java
public String getPortalPageName() {
    String viewId = Faces.getViewId();
    if (null != viewId) {
        viewId = viewId.substring(0, viewId.lastIndexOf("."));
        viewId = viewId.replaceAll("/", ".");
    }
    return viewId;
}
```

and then I can declare just once inside my template

```xhtml
<ui:param name="title" value="#{msgs['PortalPage'.concat(facesUtils.portalPageName)]}" />
```
and I automatically have a title and a breadcrumb on each page. Of course the message pattern has to match the view ids.
