### ISSUE TITLE
Mojarra 2.3.4 issues

### ISSUE THREAD

**Issue by persapiens** [adminfaces/admin-template#55]
##### Issue Overview

[Admin Boot](https://github.com/persapiens/admin-boot) does not work with mojarra 2.3.4.
Please [look discussion here](https://github.com/joinfaces/joinfaces/pull/459) about how to solve it.

##### Current Behaviour

    Submitting button does not work. Ajax fails.

##### Expected Behaviour

    Ajax does not work.

##### How to reproduce  

* run project with `java -jar target/admin-boot-3.1.2-SNAPSHOT.jar`
* access http://localhost:8080
* type your name and press button

##### Additional Information

* AdminFaces version:  1.0.0-RC13
* PrimeFaces version: 6.2
* JoinFaces version: 3.2.0-SNAPSHOT

**Comment by persapiens** [comment]
hi @rmpestano,

I confirm master branch works with mojarra 2.3.4.

Do you plan other changes before release `1.0.0-RC14`?

I look forward your answer.

**Comment by rmpestano** [comment]
Hi @persapiens,

I also tested admin-boot and is working for me also. 

I plan to release RC14 now, within next minutes it should be on maven central.

**Comment by rmpestano** [comment]
Done: https://oss.sonatype.org/content/repositories/releases/com/github/adminfaces/admin-template/1.0.0-RC14/

Thank you very much for your help on the SpringBoot integration!
