### ISSUE TITLE
AjaxStatus hangs on some components in JavaEE 8 servers

### ISSUE THREAD

**Issue by rmpestano** [adminfaces/admin-template#57]
##### Issue Overview

On **Glassfish 5**, **Payara 5.181** and **WIldfly 12.0.0** (using the EE8 preview mode - -Dee8.preview.mode=true) ajaxStatus will hang after ajax request on the following components:

* AjaxStatus hangs after **datatable** pagination, after **autocomplete** shows results, **wizard** step and **schedule**:

![payara-datatable](https://user-images.githubusercontent.com/1592273/38870404-13611594-4224-11e8-848a-71234de10a79.png)

![wizzard-javaee8](https://user-images.githubusercontent.com/1592273/38870844-7178a6be-4225-11e8-9861-5319843fd886.png)

![schedule](https://user-images.githubusercontent.com/1592273/38870861-7674f898-4225-11e8-942e-3f50f21576fd.png)

No Javascript or server side errors are noticed.

A lot of other components which trigger the ajax status are working like Accordion, TabView, DragDrop, Buttons etc..
 
OBS: Also the calendar will not popup when inside a dialog.
 
##### How to reproduce  

Start [AdminShowcase](http://github.com/adminfaces/admin-showcase) in a JavaEE 8 server and use mentioned components.
 
##### Additional Information

* AdminFaces version: RC14 
* PrimeFaces version: 6.2

**Comment by jumarome** [comment]
Hi, a question the RC16 version still have this problem?

**Comment by rmpestano** [comment]
Hi @jumarome, RC15 is latest release and we still are facing it, maybe an upgrade in glassfish/wildfly JSF/Mojarra version may fix it, I didn't tried.

**Comment by cs8898** [comment]
Payara5.182 still has this issue, but adding JVM Option -Dee8.preview.mode=false didn't work for me...

**Comment by rmpestano** [comment]
Hi @cs8898, the ` ee8.preview.mode` is used for WildFly 12 or 13 server.

Yes, we still have the problem, I've recently added [admin-starter-security](https://github.com/adminfaces/admin-starter-security) which uses the JavaEE 8 apis and see that the issue persists.

We need to isolate the problem and then try to fix.

**Comment by rmpestano** [comment]
Hi guys, I've investigated a little bit and removing `Omnifaces combined resource handler` seems to fix the issue ([see this commit](https://github.com/adminfaces/admin-starter-security/commit/78fa48018d6b6a337106048492c71c19841729a3)).  

Are you using the combined resource handler? 

@cs8898 @jumarome

**Comment by rmpestano** [comment]
Alright now I got it, just **upgrade Omnifaces to v3.x** on your application to fix the issue.
