### ISSUE TITLE
span p:selectCheckboxMenu

### ISSUE THREAD

**Issue by nazarenoneto** [adminfaces/admin-template#7]
A seta do combo não fica legal quando uso "p:selectCheckboxMenu"
![image](https://cloud.githubusercontent.com/assets/923034/25413546/85b1217a-2a01-11e7-9a2d-b66d38faa1be.png)

```
<h:form prependId="false" id="formTarefas">
	<div class="ui-g ui-fluid">
		<div class="ui-g-3">
			<h:outputLabel for="usuarioFiltro" value="Usuários:" />
			<p:selectCheckboxMenu id="usuarioFiltro"
				value="#{tarefaPortalBean.userSelecionado}" label="Usuários"
				multiple="true" filter="true" filterMatchMode="startsWith"
				panelStyle="width:250px"
				converter="omnifaces.SelectItemsConverter">
				<f:selectItems value="#{tarefaPortalBean.usuarios}" var="u"
					itemLabel="#{u.name}" itemValue="#{u}" />
			</p:selectCheckboxMenu>
		</div>
	</div>
</form>
```

Outra coisa que acontece é quando marco alguns itens e depois desmarco todos
![image](https://cloud.githubusercontent.com/assets/923034/25413695/8bb19ef0-2a02-11e7-9309-889e7800fae0.png)

No bean, nos valores seleionados fica vazio, mas visualmente não limpa a seleção

**Comment by rmpestano** [comment]
Eai @nazarenoneto, valeu pelo feedback, vou dar uma olhada.

Ainda, qual versão do admin-theme você está usando? 

Se for possível, teste com  ultimo snapshot:

```
<dependency>
    <groupId>com.github.adminfaces</groupId>
    <artifactId>admin-theme</artifactId>
    <version>1.0.0-20170426.030002-212</version>
</dependency>
```

Será preciso declarar o repositório maven:

```
<repositories>
    <repository>
        <snapshots/>
        <id>snapshots</id>
        <name>libs-snapshot</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

OBS: Problemas relacionados a interface você pode abrir issues no projeto https://github.com/adminfaces/admin-teme[AdminTheme].

**Comment by nazarenoneto** [comment]
Estou usando a versão 1.0.0-RC3 do admin-theme e admin-template

Fiz a alteração da versão e continua a mesma coisa

![image](https://cloud.githubusercontent.com/assets/923034/25435823/c796da56-2a67-11e7-8d5b-f9b56339110e.png)

Só um comparativo do html gerado
![image](https://cloud.githubusercontent.com/assets/923034/25435859/ec18b412-2a67-11e7-90e4-bd904c6598e2.png)

![image](https://cloud.githubusercontent.com/assets/923034/25435867/f8e134f8-2a67-11e7-82ea-4a53bb3f6b74.png)


Depois que abri a issue foi que percebi que abri no lugar errado, na próxima eu abro no local correto.

**Comment by rmpestano** [comment]
@nazarenoneto,

você pode testar com o snapshot abaixo?

```
<dependency>
    <groupId>com.github.adminfaces</groupId>
    <artifactId>admin-theme</artifactId>
    <version>1.0.0-20170428.143651-248</version>
</dependency>
```

**Comment by nazarenoneto** [comment]
Não deu certo...
Fique procurando aqui no css  e quando tirei esse margin-top ficou normal

![image](https://cloud.githubusercontent.com/assets/923034/25545608/0919c432-2c36-11e7-9663-1fe350f6cc44.png)

![image](https://cloud.githubusercontent.com/assets/923034/25545572/de8f8710-2c35-11e7-8bb3-cb0bb21065af.png)

**Comment by rmpestano** [comment]
Hmm, chegou a limpar as caches do browser? 

Voce pode comparar com o css gerado no showcase? lá parece estar funcionando: http://adminfaces-rpestano.rhcloud.com/showcase/pages/form/forms.xhtml (procure por **Checkbox Menu Multiple**
)

OBS: A ver RC4 recem foi liberada mas deve conter as mesmas alterações do snapshot que te passei.

**Comment by nazarenoneto** [comment]
Realmente, olhei lá no showcase e estava correto, comparando com o meu, percebi que o o meu esta dentro de uma box, segue meu código:

`<div class="box box-primary">

			<div class="box-header with-border">
				<h3 class="align-center">Lista de tarefas em aberto</h3>
			</div>
			<div class="box-body">
				<h:form prependId="false" id="formTarefas">
					<div class="ui-g ui-fluid">
						<div class="ui-g-3">
							<h:outputLabel for="usuarioFiltro" value="Usuários:" />
							<p:selectCheckboxMenu id="usuarioFiltro"
								value="#{tarefaPortalBean.userSelecionado}" label="Usuários"
								multiple="true" filter="true" filterMatchMode="startsWith"
								panelStyle="width:250px"
								converter="omnifaces.SelectItemsConverter"
								disabled="#{!tarefaPortalBean.isPesquisaUsuario()}">
								<f:selectItems value="#{tarefaPortalBean.usuarios}" var="u"
									itemLabel="#{u.name}" itemValue="#{u}" />
							</p:selectCheckboxMenu>
						</div>
						<div class="ui-g-3">
							<h:outputLabel for="situacaoFiltro" value="Situações:" />
							<p:selectCheckboxMenu id="situacaoFiltro"
								value="#{tarefaPortalBean.situacaoSelecionado}"
								label="Situações" multiple="true" filter="true"
								style="margin-top: -8px;"
								filterMatchMode="startsWith" panelStyle="width:250px">
								<f:selectItems value="#{tarefaPortalBean.situacoes}" var="s"
									itemLabel="#{s.descricao}" itemValue="#{s}" />
							</p:selectCheckboxMenu>
						</div>
						<div class="ui-g-1">
							<h:outputLabel for="dataIniFiltro" value="Data Inicial:" />
							<p:calendar id="dataIniFiltro"
								value="#{tarefaPortalBean.dataIni}" locale="pt"
								pattern="dd/MM/yyyy" />
						</div>
						<div class="ui-g-1">
							<h:outputLabel for="dataFimFiltro" value="Data Final:" />
							<p:calendar id="dataFimFiltro"
								value="#{tarefaPortalBean.dataFim}" locale="pt"
								pattern="dd/MM/yyyy" />
						</div>
						<div class="ui-g-1">
							<p:commandButton value="Pesquisar" update="formTarefas"
								actionListener="#{tarefaPortalBean.filtrar()}" />
						</div>
					</div>
					<p:separator />
					<div class="row">
						<div class="col-md-12">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>Título</th>
										<th>Descrição</th>
										<th>Situação</th>
										<th>Prazo</th>
										<th>Ações</th>
									</tr>
								</thead>
								<tbody>
									<p:repeat value="#{tarefaPortalBean.tarefas}" var="t">
										<tr class="#{t.cor}">
											<td><h:outputText value="#{t.titulo}"
													style="font-weight: bold" /></td>
											<td><h:outputText value="#{t.descricao}" escape="false" /></td>
											<td><h:outputText value="#{t.situacao}" /></td>
											<td><h:outputText value="#{t.prazoConclusao}">
													<f:convertDateTime pattern="dd/MM/yyyy HH:mm" />
												</h:outputText></td>
											<td><p:commandButton icon="fa fa-edit" title="Editar"
													action="#{tarefaPortalBean.changeToEdit(t.codigo)}" /></td>
										</tr>
									</p:repeat>
								</tbody>
							</table>
						</div>
					</div>
				</h:form>
			</div>
		</div>`


Quando coloco fora fica normal.

Eu coloquei aqui na mão esse css:
`margin-top: -8px;`
