### ISSUE TITLE
How can I use the adm tag libraries in my maven application 

### ISSUE THREAD

**Issue by Osahamed** [adminfaces/admin-template#70]
##### Issue Overview

Netbeans doesn't detect the taglib from the depenency jar
xmlns:adm="http://github.com/adminfaces"
##### Current Behaviour
netbeans shows error in the file that the taglib adm doesn't contain (breadcrumb) for example.

##### Expected Behaviour

I need to be able to use the components in my maven project

##### How to reproduce  

add depenceny in your maven web project, and try inserting the mentioned tag lib in a xhml file and use it.

##### Additional Information

* AdminFaces version:  RC 14
* PrimeFaces version:  6.2
* JSF implementation: 2.2.x

**Comment by rmpestano** [comment]
Hi @Osahamed,

have you seen [this NetBeans issue](https://netbeans.org/bugzilla/show_bug.cgi?id=257684)?  

Looks like a NetBeans limitation, have you noticed that in other IDEs? I've tested on eclipse here:

![adm-composite](https://user-images.githubusercontent.com/1592273/40116165-2a7735f2-58e9-11e8-937f-157bff4d13d8.png)


On NetBeans it gives me "No suggestions" when I try to autocomplete.

**Comment by Osahamed** [comment]
Thank you, 
 as you mentioned this is really a bug in netbeans 8.1, but unfortunately I found it still existing in Netbeans 8.2 too.

**Comment by Osahamed** [comment]
I think if the jar file can move the admin.taglib.xml inside the resources folder, this will fix the issue, as the specs said, the tag lib needs to be inside /META-INF/resources/

**Comment by rmpestano** [comment]
I can't try it now but If you have time, just clone this relository, make the chance and do a `mvn clean install `. version RC16-SNAPSHOT should be installed on your local repository. 

Also if everything goes well you can send a pull request (in this case you need to fork this repo before).

**Comment by Osahamed** [comment]
Dear Rafael M. Pestano
I need to enable RTL in adminfaces 
can you give me any advice
