### ISSUE TITLE
Input switch doesn't toggle value of boolean property

### ISSUE THREAD

**Issue by cvetan** [adminfaces/admin-template#71]
When you use, <p:inputSwitch /> it doesn't toggle boolean value of assigned property from managed bean.

And when it is rendered upon page load you have to click twice to make it "enabled". It changes from left to right, but doesn't change to blue color first time, but second.

Adminfaces 1.0.0-RC15
Primefaces: 6.2
Odminfaces: 2.6.9
JSF 2.2

**Comment by rmpestano** [comment]
Hi, can you reproduce it on this page? http://admin-showcase-admin-showcase.7e14.starter-us-west-2.openshiftapps.com/showcase/pages/components/buttons.xhtml

**Comment by cvetan** [comment]
Where is the code of layoutMB bean class?

I copied webpage and ButtonMB, but i can't find layouMB.

**Comment by rmpestano** [comment]
There is nothing special in layoutMB, [see here](https://github.com/adminfaces/admin-showcase/blob/master/src/main/java/com/github/adminfaces/showcase/bean/ShowcaseLayoutMB.java#L22), the inputSwitch binds to boolean.

**Comment by cvetan** [comment]
I can't make page from showcase to work. After clicking switch i got bunch of errors and some null reference error. 

But i am using switch as simpe as in example at showcase. Nothing special.

Page
```
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="#{adminConfig.templatePath}"
                xmlns:h="http://xmlns.jcp.org/jsf/html"> 

    <ui:define name="title">Novi administrator</ui:define>

    <ui:define name="description">
        Novi administrator
    </ui:define>

    <ui:define name="body">
        <div class="ui-grid-col-6">
            <h:form>
                <div class="ui-flat">
                    <h:messages globalOnly="true" showDetail="true" />
                    
                    <p:panelGrid columns="2" layout="grid" styleClass="ui-fluid card">
                        <p:outputLabel for="first-name" value="Ime" />
                        <p:inputText id="first-name" value="#{addAdministratorBean.administrator.firstName}" required="true" />
                        
                        <p:outputLabel for="last-name" value="Prezime" />
                        <p:inputText id="last-name" value="#{addAdministratorBean.administrator.lastName}" required="true"/>

                        <p:outputLabel for="username" value="Korisničko ime" />
                        <p:inputText id="username" value="#{addAdministratorBean.administrator.username}" required="true"/>

                        <p:outputLabel for="email" value="Email" />
                        <p:inputText id="email" value="#{addAdministratorBean.administrator.email}" required="true"/>

                        <p:outputLabel for="password" value="Šifra" />
                        <p:password id="password" value="#{addAdministratorBean.administrator.password}" required="true"/>

                        <p:outputLabel for="active" value="Aktivan" />
                        <p:inputSwitch id="active" value="#{addAdministratorBean.toogle}"/>
                    </p:panelGrid>
                    
                    <p:panelGrid columns="2" columnClasses="ui-grid-col-6,ui-grid-col-6" layout="grid" styleClass="ui-fluid card">
                        <p:commandButton value="Sačuvaj" action="#{addAdministratorBean.save()}" styleClass="btn btn-success btn-flat"/>
                            
                        
                    </p:panelGrid>
                </div>
            </h:form>
        </div>
    </ui:define>
</ui:composition>```

Bean
```
package com.bookstore.mb.administrator;

import com.bookstore.model.Administrator;
import com.bookstore.sb.administrator.AdministratorBeanLocal;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.omnifaces.util.Messages;

/**
 *
 * @author cvetan
 */
@Named(value = "addAdministratorBean")
@RequestScoped
public class AddAdministratorBean {

    Administrator administrator;
    
    private boolean toogle;

    @EJB
    AdministratorBeanLocal administratorBean;

    /**
     * Creates a new instance of AddAdministratorBean
     */
    public AddAdministratorBean() {
        administrator = new Administrator();
        administrator.setActive(false);
    }

    public Administrator getAdministrator() {
        return administrator;
    }

    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }

    public String save() {
        System.out.println("Ime:" + administrator.getFirstName());
        System.out.println("Prezime: " + administrator.getLastName());
        System.out.println("Username:" + administrator.getUsername());
        System.out.println("Aktivan:" + administrator.getActive());
        System.out.println("Password: " + administrator.getPassword());
        
        try {
            System.out.println(this.toogle);
            
            Messages.create("Uspešno", null).detail("Administrator je uspešno sačuvan u bazi.", null).add();
            
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Greška prilikom čuvanja administratora!", ex.getMessage()));

            System.out.println("Uhvacen izuzetak");
        }

        return "/admin/dashboard.xhtml?faces-redirect=true";
    }

    public boolean isToogle() {
        return toogle;
    }

    public void setToogle(boolean toogle) {
        this.toogle = toogle;
    }

}
```

What could be wrong with it? I mean it is simple component after all.

**Comment by rmpestano** [comment]
Have you tried with @ViewScoped (org.omnifaces.cdi.ViewScoped) ?

**Comment by cvetan** [comment]
It is the same with @viewscoped.

**Comment by rmpestano** [comment]
try updating the switch via ajax:

 ```
 <p:inputSwitch id="active" value="#{addAdministratorBean.toogle}">
       <p:ajax update="@form"/>
</p:inputSwitch>
```

**Comment by cvetan** [comment]
It works like that. With AJAX update and viewscoped bean it works.

If i leave it with AJAX update and revert bean to RequestScoped i get error 500 on the page.

Shouldn't it be working without AJAX? In primefaces demo it shows example, one button with and one without AJAX.

**Comment by rmpestano** [comment]
Yes, it should. I've just commit the fix, can you try with admintheme RC16-SNAPSHOT?

```
<dependency>
 	<groupId>com.github.adminfaces</groupId>
        <artifactId>admin-theme</artifactId>
	<version>1.0.0-RC16-SNAPSHOT</version>
</dependency>
```

You can download it [from here](https://oss.sonatype.org/content/repositories/snapshots/com/github/adminfaces/admin-theme/1.0.0-RC16-SNAPSHOT/admin-theme-1.0.0-RC16-20180516.221452-25.jar)

**Comment by cvetan** [comment]
This bug is present if you add admin-template through maven dependency. 

Because as i can see maven dependency is admin-theme-rc15 and not admin-theme-rc-16. I think that is the issue. I think that should be changed. Can i override it in my project?

**Comment by cvetan** [comment]
OK i've added admin-theme dependency before admin-template, and it works like that. But i think this should be fixed.

**Comment by cvetan** [comment]
No it still misbehaves. No i've loaded edit form with switch enabled(true value), tried to toggle it, won't make the switch. You can check images bellow, when i toggle value.

![switch-1](https://user-images.githubusercontent.com/5733322/43551819-c70c975e-95e8-11e8-9551-36eb7c09329a.png)
![switch-2](https://user-images.githubusercontent.com/5733322/43551820-c72b19ea-95e8-11e8-87dd-1d1064710d03.png)

**Comment by cvetan** [comment]
No it is still the same.

My project is here: https://github.com/cvetan/bookstore

There is db, and two Netbeans projects in src folder. One is EJB module the other is web application.

**Comment by cvetan** [comment]
I don't know if you noticed this, but the application throws bunch of warnings with newer versions. For instance this omnifaces error, etc:

```
17:38:00,410 WARNING [javax.enterprise.resource.webcontainer.jsf.application.view] (default task-5) Unable to save dynamic action with clientId 'j_id2' because the UIComponent cannot be found
17:38:00,410 WARNING [javax.enterprise.resource.webcontainer.jsf.application.view] (default task-5) Unable to save dynamic action with clientId 'j_id3' because the UIComponent cannot be found
17:38:00,410 WARNING [javax.enterprise.resource.webcontainer.jsf.application.view] (default task-5) Unable to save dynamic action with clientId 'j_id4' because the UIComponent cannot be found
17:38:06,067 WARNING [javax.enterprise.resource.webcontainer.jsf.application] (default task-16) JSF1064: Unable to find or serve resource, eNorKMrMTU1LTE4ttkrOzy3Iz0vNKynWSy4uBgCDwwoX.css, from library, omnifaces.combined.
17:38:06,067 WARNING [javax.enterprise.resource.webcontainer.jsf.application] (default task-16) : java.io.IOException: Broken pipe
```

**Comment by rmpestano** [comment]
The page is trying to load a cached resource that doesn't exists anymore. 

I'll have a look on your sample project over this weekend.

**Comment by rmpestano** [comment]
Hi, about the inputSwitch I got the issue, we can't rely on the class `ui-state-active` to decide if the switch is `on`. We need to only look into `ui-inputswitch-checked`.

**Comment by rmpestano** [comment]
As it is a theme issue, details are in https://github.com/adminfaces/admin-theme/issues/164

**Comment by rmpestano** [comment]
@cvetan can you try with admin-theme RC19-SNAPSHOT? just declare the theme dependency after the template one:

```
<dependency>
            <groupId>com.github.adminfaces</groupId>
            <artifactId>admin-template</artifactId>
            <version>1.0.0-RC18</version>
        </dependency>
         <dependency>
            <groupId>com.github.adminfaces</groupId>
            <artifactId>admin-theme</artifactId>
            <version>1.0.0-RC19-SNAPSHOT</version>
        </dependency>
```

**Comment by cvetan** [comment]
Yeah, it's OK now. Thanks. :+1:
