### ISSUE TITLE
p:layout and pe:layout do not work

### ISSUE THREAD

**Issue by Kameecoding** [adminfaces/admin-template#72]
##### Issue Overview

p:layout and pe:layout do not work

##### Current Behaviour

Adding any of these layouts to the body doesn't work properly

##### Expected Behaviour

These should probably work

##### How to reproduce  

Add a layout to the body, 

    <p:layout
	 id="allContent"
	 fullPage="false"
	 style="height: 600px;"
	 widgetVar="layout_pane">
	  <p:layoutUnit
		  id="two_halves_left"
		  position="center">
	  </p:layoutUnit>
	  <p:layoutUnit
	  	  id="two_halves_right"
		  position="east">
	  </p:layoutUnit>
    </p:layout>

##### Additional Information

* AdminFaces version:  RC15
* PrimeFaces version: 6.1
* JSF implementation: 2.2

**Comment by rmpestano** [comment]
Hi @Kameecoding,

can you share any screenshot? I'm interested to see the use case of p:layout within admin-template because this template was supposed to replace p:layout.

Thanks for reporting.

**Comment by Kameecoding** [comment]
I am unable to screenshot it atm, but there isn't anything to see there, it
doesn't render at all and all layout orientations have display: none; in css

**Comment by rmpestano** [comment]
I see but can you describe your usecase with p:layout? is it just to organize/align/position content? if yes I'd recommend bootstrap grid system or PrimeFaces [grid css](https://www.primefaces.org/showcase/ui/panel/grid.xhtml).

If it is something else can you provide a sample page?

**Comment by rmpestano** [comment]
I see the `visibility:hidden` comes from a css file provided by Primefaces, AdminFaces theme doesn't style p:layout, see screenshot:

![screenshot from 2016-10-07 17-15-25](https://user-images.githubusercontent.com/1592273/40440221-d9c6f9fc-5e93-11e8-93f1-ea651189af65.png)
 
Don't know why it comes with visibility hidden but you can fix that with following css rule:

```
 <ui:define name="body">
  <style type="text/css">
           body .ui-layout-unit {
               visibility: visible;
           }
       </style>
        <p:layout style="min-width:400px;min-height:200px;">
            <p:layoutUnit position="west" resizable="true" size="100" minSize="40" maxSize="200">
                West
            </p:layoutUnit>

            <p:layoutUnit position="center">
                Center
            </p:layoutUnit>
        </p:layout>
</ui:define>
```

I don't know if it has any side effects.

**Comment by Kameecoding** [comment]
the use case is having a simple 2 pnael layout where right panel can be
closed abd the two panel can be resized horizontally,this cannot really be
achieved using the grid css, overriding the css doesn't make the components
work, just makes them visible

**Comment by rmpestano** [comment]
This issue was moved to adminfaces/admin-theme#165
