### ISSUE TITLE
Question: Fixed navbar by default

### ISSUE THREAD

**Issue by Tosken1337** [adminfaces/admin-template#79]
Is it possible to configure that the navbar is fixed by default.
Without using the control slide panel to change settings?

Thanks

**Comment by rmpestano** [comment]
Hi @Tosken1337,

not possible at the moment by will be possible in next release. I'll create an issue for customizing controlsidebar via admin-config.properties.

Thank you for the idea!

**Comment by rmpestano** [comment]
It will be implemented on #87.
