### ISSUE TITLE
Question: Disable toggle sidebar on hover

### ISSUE THREAD

**Issue by Tosken1337** [adminfaces/admin-template#80]
Hi,

is it possible to disable the sidebar toogle on hover by default?
I mean without using the controlsidebar option?

**Comment by rmpestano** [comment]
Hi @Tosken1337,

By default is desabled.

Note that after you change control sidebar options they are stored on browser local storage, see details #81 and #82.

I hope it helps.

**Comment by Tosken1337** [comment]
I have cleared the browser local storage and the cache. Still the default behaviour is that the sidebar will slide out on hover.
Did i miss something? Can i hook up somewhere in the markup to disable this?

**Comment by Tosken1337** [comment]
You can also reproduce the bug on your showcase.

1. Enable "slide out on hover" on the control sidebar
2. Disable it again
3. slide out the sidebar and hover with the mouse. It will slide out on hover even if the option is disabled.

In our case where the controlSideBar is disabled it will  always slide out on hover

**Comment by rmpestano** [comment]
Yea, this is a AdminLTE limitation, they don't have an api for disabling this option. I've opened an issue there sometime ago: https://github.com/almasaeed2010/AdminLTE/issues/1843

**Comment by Tosken1337** [comment]
okay i see.
how did the expand on hover toogle in the control sidebar work? 
Is it only setting the localStorage var?

**Comment by rmpestano** [comment]
ExpandOnHover is enabled by this call: https://github.com/adminfaces/admin-template/blob/master/src/main/resources/META-INF/resources/js/control-sidebar.js#L135

**Comment by Tosken1337** [comment]
Ah okay, but disabling is not possible.
So we have to wait for a option to disable it from the adminlte plugin?

But it is strange that this feature is always enabled on my site even the default is false.

**Comment by rmpestano** [comment]
You see this on showcase also? 

The behaviour I see here is:

1 - Enable 'Expand sidebar on hover' via controlsidebar
2 - Disable it via controlsidebar
3 - it still expands on hover **as soon I reload the page**. After that it doesn't expand anymore.

**Comment by Tosken1337** [comment]
Turns out, that it is exactly the cause why the expand on hover is active.
This is also default on the original AdminLTE Template.
Do you know why or is there an option to use a fixed layout without 'extend on hover' effect?
Thanks

**Comment by rmpestano** [comment]
Hi,
 

> Do you know why or is there an option to use a fixed layout without 'extend on hover' effect?

  what issues you see on having `expand on hover` disabled in `fixed layout`?

**Comment by Tosken1337** [comment]
I See no issues. But somehow it is not possible.
Setting layout to fixed forces slide out on Hover.

**Comment by rmpestano** [comment]
Well I don't see this behaviour on admin-showcase, setting it to fixed layout doesn't force expand on hover. Don't know how to help here.

**Comment by Tosken1337** [comment]
Okay this is a misunderstanding.
Check the original AdminLTE Showcase (https://adminlte.io/themes/AdminLTE/)
Here you can see this behaviour.
i thought it was the same on admin-template.

**Comment by rmpestano** [comment]
I think the usage will depend on each application, that's why it will be customizable in next version.
