### ISSUE TITLE
Sidebar not scrollable on fixed layout

### ISSUE THREAD

**Issue by Tosken1337** [adminfaces/admin-template#83]
##### Issue Overview

The side bar menu is not scrollable

##### Current Behaviour

If we have a sidebar which has more content than vertical screen space the user is not able to reach the hidden menu elements

##### Expected Behaviour

The user should be able to scroll vertically

**Comment by rmpestano** [comment]
Hi, can you reproduce on admin-showcase home page?
admin-showcase-admin-showcase.7e14.starter-us-west-2.openshiftapps.com/showcase/

I tested only on mobile here and It scrolls:

![screenshot_20180628-093120](https://user-images.githubusercontent.com/1592273/42034629-047e1c4a-7ab7-11e8-9402-352e97f06669.png)

**Comment by Tosken1337** [comment]
Yes i can reproduce it on the showcase on chrome and ie

**Comment by rmpestano** [comment]
Hi @Tosken1337,

can you test with `admin-template RC16-SNAPSHOT`?

you'll need to declare maven snapshots repository:

```
<repositories>
    <repository>
        <snapshots/>
        <id>snapshots</id>
        <name>libs-snapshot</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by Tosken1337** [comment]
Thanks for this quick fix :-)
