### ISSUE TITLE
Disable loading fonts from google cdn

### ISSUE THREAD

**Issue by Tosken1337** [adminfaces/admin-template#89]
theme.css contains the import of the fonts from google web fonts:
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);

Is it possible to disable this and load the fonts from the classpath?

**Comment by rmpestano** [comment]
Yes it is possible, [see here](https://github.com/almasaeed2010/AdminLTE/issues/48). But on admin-theme it is bundled on the css. 

Please create an issue on [admin-theme](https://github.com/adminfaces/admin-theme) project.

**Comment by rmpestano** [comment]
This issue was moved to adminfaces/admin-theme#183
